language: node_js

deploy:
  provider: heroku
  api_key:
    secure: "Wv3cisZaf0srHbc99TrncV1EHJb2xRFuqtLe3K5cs17VxsazlofecNvrS9HjKx2+HzbgyEWWLvRzZOne53sBAx4zdH+gtJHkleiBS0QcVUhBHF2p92ngAhi9mYz1ZGGjZPTIhe2kEPr/xW8q4J5uyVLeGq8nen2DO6C7D1FW+gY="
  on: master

after_success:
  - gulp
  - rm -rf public/images
  - rm -rf public/css
  - rm -rf public/scripts
  - npm start