language: node_js
deploy:
  app: lukeburroughs
  provider: heroku
  api_key:
    secure: "UZY3HCW1Az3iqZAtJUBqRr4QOs9QFewuwWhU8AIbkfHw60GSzEnqd0rXHYaqnf77VQU6jHyXJwlWGv90nKSAA53hFGLEGdda8zZ19l7T/iPOF9W5HwayFCln5HN1ZVxTYUJ1f0G5MVXuJPjOna9er3clIdzM5V3aT3qDgSwkyFo="
  on: master
after_success:
  - gulp
  - rm -rf public/images
  - rm -rf public/css
  - rm -rf public/scripts